### ISSUE TITLE
FCD and LCD mainnet give back wrong parameter. But Tequila-LCD/FCD are correct

### ISSUE THREAD

**Issue by pedro-explore** [terra-money/fcd#124]
FCD gives back erroneous parameter for slash_window. Not sure where the issue is arising from. Not sure if it is a reporting issue only or if this is affecting the entire Core slashing calculation. Tequila-FCD reports correct data.

https://fcd.terra.dev/oracle/parameters
Slash_window: 432000 (blocks per month) (erroneous)

https://tequila-fcd.terra.dev/oracle/parameters
Slash_window: 100800 (blocks per week) (correct)

**Comment by hanjukim** [comment]
It is not wrong. Mainnet parameter has been updated by a proposal

**Comment by pedro-explore** [comment]
If the slash window was changed to month then you should have changed here to month not week: https://github.com/terra-money/fcd/pull/123
