### ISSUE TITLE
What is LCD here?

### ISSUE THREAD

**Issue by paulvi** [terra-money/fcd#127]
What is LCD in this context? Please point to repository

I was looking for some thegraph graph_node Ethereum analogue for terra, i.e.
for storing blockchain data into SQL for quicker access

https://github.com/graphprotocol/graph-node/blob/master/docs/images/TheGraph_DataFlowDiagram.png

However I understand, things may be different in Terra world.

**Comment by paulvi** [comment]
From https://github.com/terra-money/core#terracli

> rest-server Start LCD (light-client daemon), a local REST server

**Comment by hanjukim** [comment]
yes, you are right.q
