### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by paulvi** [terra-money/fcd#128]
Description from https://github.com/terra-money/awesome-terra
> Indexer that powers core Terra Finder and Terra Station

is still better than repository metadata:

Terra ETL + RestFul API Server
fcd.terra.dev/swagger

README has no intro what is exactly, but mentions modules:
- Collector(Indexer)
- Rest API server

What does FCD stay for? Isn't it acronym/abreviation?

**Comment by hanjukim** [comment]
Sorry for super late reply. It stands for Fat Client Daemon followed from Light Client Daemon in Tendermint.
