### ISSUE TITLE
GraphQL query for Mirror token supply needs to be updated

### ISSUE THREAD

**Issue by larry0x** [terra-money/fcd#132]
Querying `https://fcd.terra.dev/v1/circulatingsupply/mir` returns:

```json
{
  "type": "API_ERROR",
  "message": "400 - {\"errors\":[{\"message\":\"Cannot query field \\\"mirTotalSupply\\\" on type \\\"Statistic\\\". Did you mean \\\"mirSupply\\\"?\",\"locations\":[{\"line\":3,\"column\":13}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}},{\"message\":\"Cannot query field \\\"mirCirculatingSupply\\\" on type \\\"Statistic\\\".\",\"locations\":[{\"line\":4,\"column\":13}],\"extensions\":{\"code\":\"GRAPHQL_VALIDATION_FAILED\"}}]}"
}
```

Due to this error, CoinGecko currently fails to display MIR's circulating supply:

<img width="891" alt="Screen Shot 2021-09-20 at 12 02 51 AM" src="https://user-images.githubusercontent.com/26318510/133945729-15761a7f-78d4-4378-bf10-cbfdc80fb510.png">

The cause of this is that FCD uses an outdated query [here](https://github.com/terra-money/fcd/blob/main/src/service/treasury/token.ts#L93) to fetch data from Mirror's GraphQL server:

```graphql
# outdated
query statistic {
  statistic {
    mirTotalSupply
    mirCirculatingSupply
  }
}
```

This needs to be updated to

```graphql
query statistic {
  statistic {
    mirSupply {
      circulating
      staked
      liquidity
    }
  }
}
```

**Comment by hanjukim** [comment]
Thanks @larry0x. It's fixed.
