### ISSUE TITLE
API no longer works for columbus-4

### ISSUE THREAD

**Issue by juls858** [terra-money/fcd#138]
I am not sure if this is the right place to post this, but I can no longer use the public api to get columbus-4 info.

Simple query of tx api fails for columbus-4 blocks:
`curl -X GET "https://lcd.terra.dev/validatorsets/3999999" -H "accept: application/json"`

**Comment by hanjukim** [comment]
columbus-4 height started from 4724001 and you cannot query before the first height.

**Comment by juls858** [comment]
that is the columbus-5 start height

**Comment by juls858** [comment]
Are you saying that the FCD can not query before columbus-5 @hanjukim ? it seems some calls work and some don't for columbus-4.
