### ISSUE TITLE
Collector Run Block Height Error

### ISSUE THREAD

**Issue by Fahad-Mahmood** [terra-money/fcd#141]
I get this error when I run ```npm run collector``` with ```CHAIN_ID = columbus-5```

```
[ERROR]: /blocks/1 500 - {"error":"height 1 is not available, lowest height is 4724001"}
```

**Comment by maruf0011** [comment]
on columbus-5 there is no height 1. 
You need to set the start height.

**Comment by Fahad-Mahmood** [comment]
where can I set start height?

**Comment by danuzlav** [comment]
Hi @Fahad-Mahmood,
Could you please share the way to do it if you managed to find out?
Thanks!

**Comment by maruf0011** [comment]
Here https://github.com/terra-money/fcd/blob/main/src/collector/block/block.ts#L215, its looking for height 1.

**Comment by Fahad-Mahmood** [comment]
@danuzlav If you are using columbus-5, I would recommend you to use bombay branch, check the updated README there, you can set INITIAL_HEIGHT env.
