### ISSUE TITLE
What is the purpose of  fcd.terra.dev/swagger ?

### ISSUE THREAD

**Issue by nudabagana** [terra-money/fcd#150]
Greetings, 

I'm a little bit confused by the link in the repo (and other official terra resources) "fcd.terra.dev/swagger". What is the purpose of it? Should it be used for testing out endpoints or is it suitable for production use in websites? If so, does it have rate limits/up-time guarantees/any support?

**Comment by hanjukim** [comment]
1. We do have rate limits 500/10s, no up-time guarantees
2. We are deprecating FCD project/service, so general recommendation here 'use it own your risk'
3. However, https://lcd.terra.dev/swagger/ will not be deprecated. (But it also has 500req/10s rate limiting)

**Comment by nudabagana** [comment]
Thank you for the fast response! I will keep that in mind.
