### ISSUE TITLE
is there a list of publicly hosted fcd / lcd / terrad combos? do all validators host them? (COL-5)

### ISSUE THREAD

**Issue by obnoxiousish** [terra-money/fcd#151]
is there a list of publicly hosted fcd / lcd / terrad combos? do all validators host them? wondering if the one built into terra station is the only one available COL-5

**Comment by tvl83** [comment]
In the Terra discord they posted this information 

https://discord.com/channels/464241079042965516/897536156651106384/927845734785622016

![image](https://user-images.githubusercontent.com/141966/148320873-af40a455-4f50-4dd4-b9d1-7b72b8ea18e2.png)

Short answer is no, not all validators make them public.
