### ISSUE TITLE
Collector TypeError

### ISSUE THREAD

**Issue by qyun29** [terra-money/fcd#152]
Hi,
I got an error when i run the collector by npm run coldev, 
`01-02 10:28 [ERROR]: result.flat is not a function
TypeError: result.flat is not a function
    at Object.getValidatorConsensus (/data/fcd/src/lib/lcd.ts:202:17)
01-02 10:28 [ERROR]: result.flat is not a function
TypeError: result.flat is not a function
    at getValidatorConsensus (/data/fcd/src/lib/lcd.ts:202:17)`

How can i solve this problem?

**Comment by tvl83** [comment]
I just ran into this problem and it seemed to be resolve by updating node. What version of node are you using?

**Comment by qyun29** [comment]
> I just ran into this problem and it seemed to be resolve by updating node. What version of node are you using?

I'm using v0.5.14-oracle. What version you solve the problem?

**Comment by tvl83** [comment]
not the terrad node, but nodejs and npm

![image](https://user-images.githubusercontent.com/141966/148334109-cdd2e733-7ea9-499f-9a6e-f0217d96297f.png)

i was using node v10 and updated to v16

**Comment by qyun29** [comment]
> not the terrad node, but nodejs and npm
> 
> ![image](https://user-images.githubusercontent.com/141966/148334109-cdd2e733-7ea9-499f-9a6e-f0217d96297f.png)
> 
> i was using node v10 and updated to v16

Oh It WORKS! Thanks for your help! 👍
