### ISSUE TITLE
Using this as an API?

### ISSUE THREAD

**Issue by oliverbj** [terra-money/fcd#154]
Hi all!

I am slowly dipping my toes into Terra, and saw this project. I want to built a small website (to learn), where I interact with the Terra blockchain. More specifically, I want to monitor my transactions in a dashboard kind of way.

Can I use this service as an API for that? I.e. submitting GET requests directly? 

Example: `GET https://fcd.terra.dev/v1/tx/terra.....`

Or do I need to fork it, and run the project myself?

**Comment by tvl83** [comment]
fcd.terra.dev is available to the public so you can use that. To run fcd yourself it takes a lot of hard drive space. over 150GB to store in the db (as of nov 24th). 

I write scripts to retrieve data from the chain and use the public fcd server. 

I also plan on running a public mirror for the fcd. 

i recommend joining the terra discord for more information. I asked for an SQL dump and they had it available https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/fcd-2021-11-24.dump.gz it's 156GB but would save A LOT of time to pull all the data from the chain. this dump is from Columbus-1.

**Comment by hanjukim** [comment]
Here's newer dump: https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/fcd-2022-01-07.dump.gz

**Comment by tvl83** [comment]
@hanjukim when I try to download the SQL dump it says access denied

![image](https://user-images.githubusercontent.com/141966/150462209-76a27103-d82a-4cd2-9028-210ad0f711b3.png)
