### ISSUE TITLE
API_ERROR : "syntax error at or near \")\"","code":"42601

### ISSUE THREAD

**Issue by abdullah-almesbahi** [terra-money/fcd#157]
When I create any new wallet. I will not be able to access to this URL 
https://bombay-fcd.terra.dev/v1/txs?account=terra1cv9n8e5ut4l8ts3wa29wgs2edrcycwn29ytn3a

it shows me this error
```
{"type":"API_ERROR","message":"syntax error at or near \")\"","code":"42601"}
```

But if I transfer money to this wallet , then it going to works fine

**Comment by hanjukim** [comment]
It does not happen in my end.

**Comment by muratso** [comment]
This error is indeed happening. But it only happens if the queried account has 0 txs in it.
Check it out, here's an example https://fcd.terra.dev/v1/txs?account=terra1ynhsjzegav33y5a3094yw0yj68s7ym64s0r2nv&limit=100
