### ISSUE TITLE
Is there an endpoint or some request that can be performed to check the FCD height?

### ISSUE THREAD

**Issue by muratso** [terra-money/fcd#158]
We would like to monitor the FCD height and make sure it will never get too behind of the LCD.
The endpoints `/blocks/latest`, `/node_info`, `/cosmos/base/tendermint/v1beta1/node_info`, and `/cosmos/base/tendermint/v1beta1/blocks/latest` only show the node height, but we're not sure on how to monitor the FCD height (without having to check the logs).

**Comment by hanjukim** [comment]
All of endpoints you mentioned are not implemented in FCD project, but LCD (Lite Client Daemon) of Cosmos SDK. I recommend you to use `/cosmos/base/tendermint/v1beta1/blocks/latest` of LCD.
