### ISSUE TITLE
Recommended mem/cpu for PG Database

### ISSUE THREAD

**Issue by muratso** [terra-money/fcd#163]
What are the recommended requirements mem/cpu/disk for the postgres database?

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by muratso** [comment]
Seems legit... @hanjukim

**Comment by DevElliett** [comment]
Visit the official support for further assistance

**Comment by hanjukim** [comment]
@muratso Oh no.. I blocked DevElliett

**Comment by muratso** [comment]
Thanks for blocking the spam and for the answer. 🙂 Excited for this new project.

**Comment by joaophi** [comment]
> @muratso Oh no.. I blocked DevElliett. Recommend requirements mem/cpu are depends on how much load you have. We are using Aurora PostgreSQL 1 writer, 3 reader with db.r6g.4xlarge. Compressed dump size is now at around 200GB.
> 
> Btw, we are working on new project which provides core features of this project. (block/tx/historical txs by address, etc.)

Hey, where can we find info about this new project? And do you have a newer dump?
