### ISSUE TITLE
Querying accounts with no TXs throws a 500 error 

### ISSUE THREAD

**Issue by muratso** [terra-money/fcd#169]
Since a new "FCD" is being developed, not sure how much effort you guys want to spend on this but... querying accounts with no TXs in it (newly created accounts) result in the following error
```
{
  "type": "API_ERROR",
  "message": "syntax error at or near \")\"",
  "code": "42601"
}
```

Here are a few accounts that you can get this error:

https://fcd.terra.dev/v1/txs?account=terra18jfafdr6uldarmhtt2phqx2qumc7znja952c57&limit=100
https://fcd.terra.dev/v1/txs?account=terra1ynhsjzegav33y5a3094yw0yj68s7ym64s0r2nv&limit=100

**Comment by robiso50** [comment]
Hello @muratso  , A support ticket has been opened for you with Support ticket number TB7839HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by muratso** [comment]
These scam tentatives are becoming quite annoying 😆 .
cc: @hanjukim

**Comment by hanjukim** [comment]
I am on it thanks
